# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

# automation: !include automations.yaml
# script: !include scripts.yaml
# scene: !include scenes.yaml

logger:
  default: "info"

cover:
  - platform: template
    covers:
      vertical_blind:
        device_class: blind
        value_template: "{{is_state('input_boolean.test_service','on')}}"
        position_template: "{{states('input_number.cover_position')|int}}"
        set_cover_position:
          service: input_number.set_value
          data:
            entity_id: "input_number.cover_position"
            value: "{{position}}"